language: python
dist: xenial
python: '3.7'
install:
- pip install pipenv
- pipenv sync -d
- pip install codecov
script:
- flake8
- pytest --cov=app
after_success: codecov
before_deploy:
- docker build -t docker.io/graffic/dlg .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push docker.io/graffic/dlg
deploy:
  edge: true
  provider: bluemixcloudfoundry
  api: https://api.eu-gb.bluemix.net
  username: javier.gonel@glispamedia.com
  password:
    secure: Kvqln+wFmNx72wIpFhf3bR3oXC37Q6OISSOd080LE3cX++93UIQIAnIGnbX5qzfBusXmqgVuIkZT+znvhNl7NgKMvy0gBOCs23n6awO03xqHtvxdvGICzstJ85kurtS3Zmct+keuX3Ws4K+d12d0BBp5JomVeiO1njJbZecp+YdKaUwK1Hcx4vIyZMPWUpuEefwhlZfwpvQLxaDaGGYPShn1mVSIYv46xqI1bOPG2FOWuoBqTxzClZe7RNUfiDuITGLBTxhGbLbPWFiEErcPFRazyrjk1WhXRhcWGp9rLZpDgoxzFsxIDmhQanuQTXiGxQPGn7dZF4No5WBw1a0S8Vzi+Wr9q21KR9LjR1N6fw2YKmeMj/0IUrtqhIMARzD9+XC25FnMTf3+4NocZDITOI76me7jHbfXk5t0APGxolfBWgEjTYQwSbT1fbKRxORzzrJPA89HIH1SP7HJmAOSvdIVZnPjBtZFYrK+BhuhsIRK7C2iL4C0qQylVWY6MEH2SBsjjZ4Uo/PHaV1kr6fk9h+MZKrm1KyNeRQd/TLM8281BxFckIXawuIVb5vISERR4s0o4pKQN2yC8JbRGhxTDZ60A031wNcUiL2q24yiUg/e7aLZqMG3xq/jXmwfgKNbAXIxXjcC3ior18AWDVNYwOOIBZyqPfjoh864jmyz9gA=
  organization: javier.gonel@glispamedia.com
  space: dev
  manifest: cloudfoundry-manifest.yml
  region: eu-gb
  on:
    branch: master
